[pytest]
pythonpath = .
filterwarnings =
    ignore:Using httpx with starlette.testclient is deprecated.*:DeprecationWarning
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning
    ignore:.*on_event.*is deprecated.*:DeprecationWarning
